name: CI
on:
  push:
  pull_request:

jobs:
  backtest-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-strict.txt
          pip install ruff
      - name: Ruff lint
        run: ruff check .
      - name: Run tests
        run: pytest
      - name: Backtest pipeline
        run: |
          python -c '
from src import data_prep, strategy
assert data_prep.load_data("tests/fixtures/EURUSD_M15_sample.csv")
assert strategy.generate_signals() == []
'
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-strict.txt || true
          pip install ruff black pytest pytest-cov
      - name: Lint
        run: ruff check --select E,F .
      - name: Test
        run: pytest --cov=src --cov-fail-under=90
  backtest-ci:
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install ruff pytest
      - name: Quick back-test
        run: |
          python -c '
from src import data_prep, strategy
assert data_prep.load_data("tests/fixtures/EURUSD_M15_sample.csv")
assert strategy.generate_signals() == []
'